# Generated by Django 4.2.6 on 2023-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_like_delete_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="like",
            new_name="likes",
        ),
    ]
