# Generated by Django 4.2.6 on 2023-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_content_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="comments/images/"
            ),
        ),
    ]
