# Generated by Django 4.2.6 on 2023-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_comment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
