# Generated by Django 4.2.6 on 2023-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(null=True, upload_to="comments/images/"),
        ),
    ]
