# Generated by Django 4.2.6 on 2023-11-19 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_message_delete_chatroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
