# Generated by Django 4.2.6 on 2023-11-22 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0014_room_chatgroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Room",
            new_name="ChatRoom",
        ),
        migrations.RenameModel(
            old_name="ChatGroup",
            new_name="RoomMessage",
        ),
    ]
