# Generated by Django 4.2.6 on 2023-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_roommessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="room-messages/images/"
            ),
        ),
    ]
