# Generated by Django 4.2.6 on 2023-11-25 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0020_chatmessage_video_roommessage_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="chat_domain",
        ),
    ]
