# Generated by Django 4.2.6 on 2023-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0021_remove_chatmessage_chat_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="room-messages/cover-pic/"
            ),
        ),
    ]
