# Generated by Django 4.2.6 on 2023-11-18 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Personal Chat",
            },
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
    ]
