# Generated by Django 4.2.6 on 2023-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0019_remove_chatmessage_slug_chatmessage_chat_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="room-messages/videos/"
            ),
        ),
        migrations.AddField(
            model_name="roommessage",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="messages/videos/"),
        ),
    ]
