# Generated by Django 4.1 on 2023-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
