# Generated by Django 4.2.6 on 2023-11-07 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0013_alter_groupmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="MembershipRequest",
        ),
    ]
