# Generated by Django 4.2.6 on 2023-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0017_alter_messagegroup_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagegroup",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="messagegroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
