# Generated by Django 4.2.6 on 2023-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0022_groupcomment_groupreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupcomment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="group_comments/images/"
            ),
        ),
    ]
