# Generated by Django 4.2.6 on 2023-11-04 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0002_friendship_follow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower",)},
        ),
        migrations.RemoveField(
            model_name="follow",
            name="followee",
        ),
    ]
