# Generated by Django 4.2.6 on 2023-11-05 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0004_grouppost_group_description_delete_follow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="group_posts/images/"
            ),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="likes",
            field=models.ManyToManyField(
                related_name="group_posts_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="grouppost",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="group_posts/videos/"
            ),
        ),
        migrations.AlterField(
            model_name="grouppost",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
