# Generated by Django 4.2.6 on 2023-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_grouppost_image_grouppost_likes_grouppost_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="group_pic/images/"
            ),
        ),
    ]
