# Generated by Django 4.2.6 on 2023-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0009_alter_group_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="is_creator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
