# Generated by Django 4.2.6 on 2023-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0010_groupmembership_is_creator_groupmembership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
