# Generated by Django 4.2.6 on 2023-11-07 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0011_groupmembership_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmembership",
            name="message",
        ),
    ]
