# Generated by Django 4.2.6 on 2023-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0015_messagegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroup",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
