# Generated by Django 4.2.6 on 2023-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0016_messagegroup_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagegroup",
            name="is_confirmed",
            field=models.BooleanField(blank=True),
        ),
    ]
