# Generated by Django 4.2.6 on 2023-11-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0018_remove_messagegroup_is_confirmed_messagegroup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroup",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.grouppost",
            ),
        ),
    ]
